spring:
  application:
    name: "Journal Application"
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: journaldb
      auto-index-creation: true

server:
  port: 8081

#    servlet :
#      context-path: /Journal
